define: DUK_USE_PARANOID_MATH
introduced: 1.0.0
default: false
tags:
  - portability
description: >
  Rely as little as possible on compiler behavior for NaN comparison,
  signed zero handling, etc.  May be needed for (very) broken compilers.
